### ISSUE TITLE
Turning Allowance

### ISSUE THREAD

**Issue by daheise** [dga711/msfs-fscaptain#1]
>A few nm before any waypoint, the SimRate will decrease to allow the autopilot to properly adjust heading. SimRate will increase after the waypoint again.

I would suggest changing such that there is time *after* the waypoint where the sim rate is kept low. In my experience the sim rate is low before the turn, but turns up as soon as the turn starts (i.e. the waypoint is passed).

**Comment by dga711** [comment]
I remember thinking about that when i coded the app. Will look into it. 
Thanks for the feedback!

**Comment by dga711** [comment]
Using cross track error and distance in 1.0.2
