### ISSUE TITLE
Auto Pause on T/D

### ISSUE THREAD

**Issue by edge33** [dga711/msfs-fscaptain#3]
Can I suggest to add a feature that pauses the sim (not Active pause) when at a given distance from the last wp ?

**Comment by dga711** [comment]
That one is actually on my list. Just didn't get to it yet. Will work on it pretty soon.

**Comment by edge33** [comment]
Contact me if you would like to accept help

**Comment by dga711** [comment]
> Contact me if you would like to accept help

@edge33 Sure. I have some changes already in the pipeline but don't really get to work on it since I am heads deep into the WT CJ4.
Do you have Discord? dga#6992

**Comment by dga711** [comment]
Outside and in a generic way we can really only get the direct distance to destination which would be highly inaccurate to calculate the TOD.
I guess there is ways to grab the whole flightplan via SimConnect, but this is out of scope for the work I am willing to put into this tool ;)
